version: 2.1
commands:
  setup-cd:
    steps:
      - run:
          name: Configure environment
          command: |
            # Install Terraform
            curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
            sudo unzip terraform.zip -d /usr/local/bin/

            # Install Ansible
            sudo apt install ansible

            # Install AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install


jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup-cd

      - run: 
          name: Package up Infrastructure as Code (IAC) and scripts
          command: |
            cp -r infra artifacts/infra
            cp -r ansible artifacts/ansible

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts     

  deploy-test:
    docker:
      - image: cimg/base:2020.01
    environment:
      ENV: test
    steps:
      - attach_workspace: 
          at: ./

      - setup-cd

      - run:
          name: Deploy infrastructure
          command: |
            cd artifacts/infra
            make init
            make up

      - run:
          name: Run script to generate environment variables and execute Ansible Playbook
          command: |
            cd artifacts/ansible
            ./run_ansible.sh
                  

  # deploy-prod:


workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
      - approval: 
          type: approval
          requires:
            - deploy-test
      # - deploy-prod:
      #     requires:
      #       - approval