version: 2.1
commands:
  setup-cd:
    steps:
      - run:
          name: Configure environment
          command: |
            # Install Terraform
            curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
            sudo unzip terraform.zip -d /usr/local/bin/

            # Install AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install


jobs:
  build:
    machine: true
    environment:
      ECR: 208973674356.dkr.ecr.us-east-1.amazonaws.com
      reponame: app
    steps:
      - checkout
      - setup-cd


      # - run:
      #     name: Install dependencies
      #     command: |
      #       # Install AWS CLI
      #       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #       unzip awscliv2.zip
      #       sudo ./aws/install


      - run: 
          name: Build Docker image & push to registry
          command: |
            mkdir artifacts
            export IMAGE_TAG=${ECR}/${reponame}:${CIRCLE_SHA1}
            echo ${IMAGE_TAG} > artifacts/image.txt
            docker build -t ${IMAGE_TAG} .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR}
            docker push ${IMAGE_TAG}


      - run: 
          name: Package up Infrastructure as Code (IAC) and scripts
          command: |
            cp -r infra artifacts/infra


      - persist_to_workspace:
          root: ./
          paths:
            - artifacts     

  deploy-app:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace: 
          at: ./

      - setup-cd

      - run:
          name: Deploy infrastructure
          command: |
            cd artifacts/infra
            make init
            make up
            

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy-app:
          requires:
            - build