- name: Deploy Application
  hosts: all
  tasks: 
    # - name: Ensure apache is installed
    #   become: yes
    #   package:
    #     name: httpd
    #     state: present

    # - name: Ensure apache service is running
    #   become: yes
    #   service: 
    #     name: httpd
    #     state: started
    #     enabled: yes


    - name: Check if the release file of the app exists
      stat:
        path: /tmp/TechTestApp_v.0.6.0_linux64.zip
      register: release_file
    - debug:
        var: release_file


    - name: Download app release to EC2 instance to tmp directory
      become: yes
      get_url:
        url: "https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip" # local path to release file 
        dest: /tmp
        mode: '0644'
      when: not release_file.stat.exists
      register: download_result
    - debug:
        var: download_result


    - name: Check if the app directory exists
      stat:
        path: /etc/app
      register: app_dir
    - debug:
        var: app_dir.stat.exists
      

    - name: Create app directory if it does not exist
      become: yes
      shell: "cd /etc && mkdir app"
      when: not app_dir.stat.exists

      
    - name: Check if the dist directory exists
      stat:
        path: /etc/app/dist
      register: dist_dir
    - debug:
        var: dist_dir.stat.exists


    - name: Unzip the release file, if the application has not been already installed
      become: yes
      unarchive:
        src: /tmp/TechTestApp_v.0.6.0_linux64.zip
        dest: /etc/app
        remote_src: yes
      when: not dist_dir.stat.exists
      register: install_result
    - debug:
        var: install_result

    
    - name: Include environment varibles file    
      include_vars: external_vars.yml


    - name: Override environment variables for conf.toml and run TechTestApp updatedb -s
      become: yes
      shell: |
        export VTT_DBUSER={{ db_user }}
        export VTT_DBPASSWORD={{ db_pass }}
        export VTT_DBHOST={{ db_endpoint }}
        export VTT_LISTENHOST=0.0.0.0
        export VTT_LISTENPORT=80
        ./TechTestApp updatedb -s
      args:
        chdir: /etc/app/dist
      register: updatedb_result
    - debug:
        var: updatedb_result